### PR TITLE
Changes

### PR DESCRIPTION
**Pull request by zbazztian**
@Cosydays Here are my changes to your project and query.

The main problem was [this](https://github.com/Cosydays/codeql_demo/blob/4b8b60b69a973e0c8d9c0207c78164f8fcfc87d1/test.ql#L91) code, which matches the regular expression on the type of the field (`FieldValue`'s type is `string` so it doesn't match). I changed it so that it matches on the field's qualified name instead.

I also slightly changed your project, because it didn't compile for me. Note that if the `model` and `rpc_sdk` modules are included in the analyzed source code, then you will likely not need [this](https://github.com/Cosydays/codeql_demo/blob/4b8b60b69a973e0c8d9c0207c78164f8fcfc87d1/test.ql#L6-L21) code. Unless they are external, then you might indeed need it.

### CODE REVIEW

**Comment by zbazztian** [comment]
Note that you will have to rebuild your database (`codeql database create ...`) after merging this pull request.

**Comment by Cosydays** [comment]
> @Cosydays Here are my changes to your project and query.
> 
> The main problem was [this](https://github.com/Cosydays/codeql_demo/blob/4b8b60b69a973e0c8d9c0207c78164f8fcfc87d1/test.ql#L91) code, which matches the regular expression on the type of the field (`FieldValue`'s type is `string` so it doesn't match). I changed it so that it matches on the field's qualified name instead.
> 
> I also slightly changed your project, because it didn't compile for me. Note that if the `model` and `rpc_sdk` modules are included in the analyzed source code, then you will likely not need [this](https://github.com/Cosydays/codeql_demo/blob/4b8b60b69a973e0c8d9c0207c78164f8fcfc87d1/test.ql#L6-L21) code. Unless they are external, then you might indeed need it.

In a real code repository, rpc_sdk is an external package, not included in the source code. So, I think [this](https://github.com/Cosydays/codeql_demo/blob/4b8b60b69a973e0c8d9c0207c78164f8fcfc87d1/test.ql#L6-L21) code is needed. Is there a more elegant way to write this paragraph？

**Comment by zbazztian** [comment]
You could rewrite the constructor as follows:

```codeql
    FunctionModels() {
      functionInput.isParameter([0 .. 7]) and
      functionOutput.isResult([0 .. 7])
    }
```
Note, however, that this is very aggressive and might lead to false positive results. Ideally, you would only model those functions which actually do have flow from some of their parameters to their return values. I think in the given example those are mostly the getters such as `GetEmail()`, `GetUserId()`, etc.

**Comment by Cosydays** [comment]
Unfortunately, I don't have that information. What I know is exactly what I described to you in the document: the field `Email` of method `UpdateEmail` is tainted

**Pull request merged**
